### ISSUE TITLE
Getting FAILED CONFIGURATION: error while compiling on PhantomJSDriver script

### ISSUE THREAD

**Issue by tiki11** [tabhresh/Edureka_4thMay#1]
package Module12;

import org.testng.annotations.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterSuite;

public class HeadlessBrowser {
  
	  //Initiate WebDriver
    WebDriver driver;
	
  @BeforeTest
  public void OpenBrowser()
  {
		System.setProperty("phantomJS.binary.path", "C:\\SELENIUM\\Exe Files and Drivers\\phantomjs.exe");
		driver = new PhantomJSDriver();
		
		driver.get("http://www.google.com"); 
    }
  

	@Test
public void Search() throws InterruptedException
{
	    driver.findElement(By.name("q")).sendKeys("Edureka");
		
		driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
		
		Thread.sleep(3000);
		String Title = driver.getTitle();
		
		//Value of Title = Edureka - Google Search
		System.out.println(Title);	  
	}
 
  @AfterSuite
  public void CloseBrowser()
  {
	  driver.quit();

  }
}

**Comment by tabhresh** [comment]
the path of the driver is incorrect as we put the path with a double backward slash ( \\ ) .

**Comment by tiki11** [comment]
Hello Abhresh,
I am not sure why but when i copy/pasted the code to git, it changed to
single slash. In eclipse, I have it as double slashes (like this)...Do you
see any other issue?



package Module12;

import org.testng.annotations.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterSuite;

public class HeadlessBrowser {

 //Initiate WebDriver
    WebDriver driver;

  @BeforeTest
  public void OpenBrowser()
  {
System.setProperty("phantomJS.binary.path", "C:\\SELENIUM\\Exe Files and
Drivers\\phantomjs.exe");
driver = new PhantomJSDriver();

driver.get("http://www.google.com");
    }


@Test
public void Search() throws InterruptedException
{
   driver.findElement(By.name("q")).sendKeys("Edureka");

driver.findElement(By.name("q")).sendKeys(Keys.ENTER);

Thread.sleep(3000);
String Title = driver.getTitle();

//Value of Title = Edureka - Google Search
System.out.println(Title);
}

  @AfterSuite
  public void CloseBrowser()
  {
 driver.quit();

  }
}
